#!/usr/bin/env sh
# One-shot bootstrap for a production deploy.
# Idempotent: re-running preserves existing secrets unless you pass --reset.

set -eu

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

RESET=0
for arg in "$@"; do
  case "$arg" in
    --reset) RESET=1 ;;
    -h|--help)
      cat <<EOF
Usage: ./scripts/setup.sh [--reset]

  --reset    Wipe existing ./secrets and generate fresh ones. Leaves ./data alone.

Interactive. Prompts for AUTH_URL. Generates master_key + cron_secret.
Writes .env. Does NOT configure a reverse proxy — that's your job.
EOF
      exit 0 ;;
  esac
done

mkdir -p data secrets
chmod 700 secrets

if [ "$RESET" = "1" ]; then
  echo "→ --reset: wiping ./secrets/"
  rm -f secrets/master_key secrets/cron_secret
fi

# ─── AUTH_URL ──────────────────────────────────────────────────────
if [ -f .env ] && grep -q "^AUTH_URL=" .env && [ "$RESET" != "1" ]; then
  AUTH_URL="$(grep '^AUTH_URL=' .env | head -1 | cut -d'=' -f2- | tr -d '"')"
  echo "→ keeping existing AUTH_URL=${AUTH_URL}"
else
  printf "Public URL for your nudge install (e.g. https://nudge.example.com): "
  read -r AUTH_URL
  AUTH_URL="$(echo "$AUTH_URL" | tr -d ' ')"
  if [ -z "$AUTH_URL" ]; then
    AUTH_URL="http://localhost:3000"
    echo "  (no input — defaulting to ${AUTH_URL} for local testing)"
  fi
fi

# ─── secrets ───────────────────────────────────────────────────────
gen() {
  openssl rand -base64 32 2>/dev/null || \
    node -e "console.log(require('crypto').randomBytes(32).toString('base64'))"
}

if [ ! -s secrets/master_key ]; then
  gen > secrets/master_key
  chmod 600 secrets/master_key
  echo "✓ generated ./secrets/master_key"
else
  echo "→ keeping existing ./secrets/master_key"
fi

if [ ! -s secrets/cron_secret ]; then
  gen > secrets/cron_secret
  chmod 600 secrets/cron_secret
  echo "✓ generated ./secrets/cron_secret"
else
  echo "→ keeping existing ./secrets/cron_secret"
fi

# ─── .env ──────────────────────────────────────────────────────────
cat > .env <<EOF
# Generated by ./scripts/setup.sh — safe to re-run
AUTH_URL=${AUTH_URL}
EOF
echo "✓ wrote .env"

# ─── next steps ────────────────────────────────────────────────────
cat <<EOF

──────────────────────────────────────────────────────────────────
Setup complete.

1.  docker compose up -d --build

2.  nudge listens on 127.0.0.1:3000 of this host.
    Point your reverse proxy (Caddy / nginx / Traefik / Cloudflare Tunnel)
    at localhost:3000. Terminate TLS there. Ensure the public URL matches
    AUTH_URL=${AUTH_URL} so cookies and sessions work.

3.  Open ${AUTH_URL} — you'll land on the first-boot setup wizard.

──────────────────────────────────────────────────────────────────
EOF
